added nextjs Dockerfile

diff --git a/next/Dockerfile b/next/Dockerfile
--- a/next/Dockerfile
+++ b/next/Dockerfile
@@ -1,26 +1,52 @@
-# nextjs/Dockerfile
+# syntax=docker.io/docker/dockerfile:1
 
-# Etapa de build
-FROM node:16-alpine AS builder
+FROM node:18-alpine AS base
 
-WORKDIR /usr/src/app
+# 1. Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 
-COPY package.json yarn.lock ./
-RUN yarn install
+WORKDIR /app
 
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# 2. Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-RUN yarn build
+# This will do the trick, use the corresponding env file for each environment.
+COPY .env.production.sample .env.production
+RUN npm run build
 
-# Etapa de produção
-FROM node:16-alpine
+# 3. Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
 
-WORKDIR /usr/src/app
+ENV NODE_ENV=production
 
-COPY --from=builder /usr/src/app/.next ./.next
-COPY --from=builder /usr/src/app/node_modules ./node_modules
-COPY --from=builder /usr/src/app/package.json ./
-COPY --from=builder /usr/src/app/public ./public
+RUN addgroup -g 1001 -S nodejs
+RUN adduser -S nextjs -u 1001
+
+COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
 
 EXPOSE 3000
 
-CMD ["yarn", "start"]
+ENV PORT=3000
+
+CMD HOSTNAME="0.0.0.0" node server.js
